import Head from "next/head";
import Breadcrumb from "../../components/breadcrumb/breadcrumb";
import Footer from "../../components/footer";
import Nav from "../../components/nav";
import ReferralCode from "./componets/referralCode/referralCode";
import FriendsWhoEnrolledCard from "./componets/card/friendsWhoEnrolledCard";
import Back from "@/pages/components/button/back";

interface LinkProps {
    title: string;
    link: string;
}

export default function Page() {

    const footerLinks: LinkProps[] = [
        {
            title: "Terms & Conditions",
            link: "/terms"
        }
    ]

    return (
        <>
        <Head>
            <title>Friends Who Enrolled</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
            <div className="parent">
                <div className="sticky">
                    <Nav />
                    <Breadcrumb />
                </div>
                <main className="container">
                    <Back />
                    <ReferralCode />
                    <FriendsWhoEnrolledCard />
                    <Footer links={footerLinks} />
                </main>
            </div>
        </>
    )
}