import Head from "next/head";
import Breadcrumb from "../components/breadcrumb/breadcrumb";
import Dashboard from "../components/card/dashboard";
import Footer from "../components/footer";
import Nav from "../components/nav";
import Work from "../components/work/work";
import Back from "../components/button/back";

interface LinkProps {
    title: string;
    link: string;
}

export default function ReferAndEarn() {

    const footerLinks: LinkProps[] = [
        {
            title: 'Friends Who Enrolled',
            link: '/refer-&-earn/friends-referred'
        },
        {
            title: "Terms & Conditions",
            link: "/terms"
        }
    ]

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="parent">
                <div className="sticky">
                    <Nav />
                    <Breadcrumb />
                </div>
                <main className="container">
                    <Back />
                    <Dashboard />
                    <Work />
                    <Footer links={footerLinks} />
                </main>
            </div>
        </>
    )
}